### ISSUE TITLE
Extracting features for a directory of images

### ISSUE THREAD

**Issue by tejas1995** [microsoft/scene_graph_benchmark#11]
I'm slightly confused by the instructions on how to extract features from the `test_sg_net.py` script - more specifically:
- what format the data directory has to be in (i.e. something more than just a directory containing images) and 
- what variables need to be set in the `sgg_configs/vgattr/vinvl_x152c4.yaml` config in order to point to my data directory (I'm not sure what the variables `DATASETS.TEST` and `DATA_DIR` need to be - I assumed the latter was the directory with all the images I need features for, but that does not seem to be the case)

**Comment by hanxiaotian** [comment]
This is a similar question to https://github.com/microsoft/scene_graph_benchmark/issues/7#. 
You can follow vinson2233 detailed comment https://github.com/microsoft/scene_graph_benchmark/issues/7#issuecomment-819357369
