### ISSUE TITLE
How to extract the scene graph?

### ISSUE THREAD

**Issue by JXT218** [microsoft/scene_graph_benchmark#12]
I would like to extract the scene graph like what is shown on R152FPN_demo.png. Which script should I try?

**Comment by hanxiaotian** [comment]
You could try following commands:
`# visualize OpenImage scene graph generation by RelDN
python tools/demo/demo_image.py --config_file sgg_configs/vrd/R152FPN_vrd_reldn.yaml --img_file demo/1024px-Gen_Robert_E_Lee_on_Traveler_at_Gettysburg_Pa.jpg --save_file demo/1024px-Gen_Robert_E_Lee_on_Traveler_at_Gettysburg_Pa_output.jpg --visualize_relation MODEL.ROI_RELATION_HEAD.DETECTOR_PRE_CALCULATED False`

**Comment by alice-cool** [comment]
> python tools/demo/demo_image.py --config_file sgg_configs/vrd/R152FPN_vrd_reldn.yaml --img_file demo/1024px-Gen_Robert_E_Lee_on_Traveler_at_Gettysburg_Pa.jpg --save_file demo/1024px-Gen_Robert_E_Lee_on_Traveler_at_Gettysburg_Pa_output.jpg --visualize_relation MODEL.ROI_RELATION_HEAD.DETECTOR_PRE_CALCULATED False

I run your pointed code. But I got the error
No such file or directory: './datasets/openimages_v5c/vrd/vrd_frequency_prior_include_background.npy'.

May I ask that the file download link？

**Comment by nekithockey75** [comment]
You may want to read this part of the README to download all the required files.

`https://github.com/microsoft/scene_graph_benchmark#perform-training`

**Comment by tejan-rgb** [comment]
@DorianMood Were you able to generate scene graph  for an image?

**Comment by tejan-rgb** [comment]
@hanxiaotian Could you please help? Not able to understand how to generate scene graphs.
