### ISSUE TITLE
Download vinvl pre-training model

### ISSUE THREAD

**Issue by wangyanan326** [microsoft/scene_graph_benchmark#14]
I failed to used azcopy command to download vinvl pre-training model. Could you show me how to download pretraining models? Thank you!

./azcopy cp https://penzhanwu2.blob.core.windows.net/results/vinvl/od_models/vinvl_vg_x152c4.pth .

INFO: Scanning...

failed to perform copy command due to error: Login Credentials missing. No SAS token or OAuth token is present and the resource is not public.

**Comment by pzzhang** [comment]
The link above is not public. Please use the following link to download the model.

# extract vision features with VinVL object-attribute detection model
# pretrained models at https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/vinvl_model_zoo/vinvl_vg_x152c4.pth
# the associated labelmap at https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/vinvl_model_zoo/VG-SGG-dicts-vgoi6-clipped.json

**Comment by KosukeTrue** [comment]
still cannot download the model file

**Comment by mogumogu2333** [comment]
Cannot download the pretrain model.

`./azcopy copy https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/vinvl_model_zoo/vinvl_vg_x152c4.pth .`

Error message like:
```
INFO: Scanning...
INFO: Proxy detected: https://azcopyvnextrelease.blob.core.windows.net -> http://sys-proxy-rd-relay.byted.org:8118
INFO: Authenticating to source using Azure AD

failed to perform copy command due to error: no cached token found, please log in with azcopy's login command, required key not available
```

**Comment by pzzhang** [comment]
@KosukeTrue , could you try it again? It should work now.

**Comment by tt0059** [comment]
Hello， how  to download?

**Comment by pzzhang** [comment]
Just updated the links to copts. Please check it out here https://github.com/pzzhang/VinVL/blob/main/README.md

Best,
Pengchuan

**Comment by XiaoyiHan6** [comment]
Hello，where is weight of model??
![image](https://github.com/user-attachments/assets/5f7a9768-ead1-4de7-9fa7-02c04b3939be)
and，I found that the way I copied before was wrong, and now I copy again without the weight of the model.
I run this code: azcopy copy 'https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/datasets/openimages_v5c' 'D:\PycharmProject\Open-VidSGG\SGB_checkpoints' --from-to=PipeBlob --recursive
, the result is that:
![image](https://github.com/user-attachments/assets/cb488150-11f0-4f78-bbfb-042704eabe2b)
