### ISSUE TITLE
MIssing links to pre-trained model checkpoints

### ISSUE THREAD

**Issue by coldmanck** [microsoft/scene_graph_benchmark#20]
The download links to [Pre-trained models' checkpoints of Openimages V5](https://github.com/microsoft/scene_graph_benchmark/blob/main/SCENE_GRAPH_MODEL_ZOO.md) show **File Not Found Errors**. Could please take a look and provide new links?

**Comment by hanxiaotian** [comment]
Sorry for the trouble, removed those models by accident. Could you please try again? It should work right now. Thanks
