### ISSUE TITLE
VinVL can model the relation prediction?

### ISSUE THREAD

**Issue by alice-cool** [microsoft/scene_graph_benchmark#22]
I found VinVL 'S object and attribute lable is so bigger. So How to use the VinVL  in  predicate classification. At Now the project only provides 150 object. But visual genome +faster rcnn can detect 1370 object class. It is so big difference.

**Comment by alice-cool** [comment]
sgcls maybe not right. The code running failed

**Comment by alice-cool** [comment]
if we don't provide relations we will get the following "exception"
AttributeError: 'SceneParser' object has no attribute 'relation_head'

**Comment by alice-cool** [comment]
![image](https://user-images.githubusercontent.com/16870890/123068369-69a1ad00-d444-11eb-9b8a-85b04d442071.png)
So the flexible label provides whether it only can constrained to the predifined 151 object label?

**Comment by alice-cool** [comment]
Dear scholar,
   Could the VinVL model can produce specific features for my designated or the grounding truth coordinate?

**Comment by hanxiaotian** [comment]
For releation predictions, you need to run our pretrained relation prediction models. You can refer to this https://github.com/microsoft/scene_graph_benchmark/issues/16#issuecomment-876623915
