### ISSUE TITLE
ModelZoo contains broken links

### ISSUE THREAD

**Issue by aleSuglia** [microsoft/scene_graph_benchmark#34]
Hi there, 

It looks like the ModelZoo contains broken links for all the OpenImages models such as:

1. https://penzhanwu2.blob.core.windows.net/phillytools/data/maskrcnn/pretrained_model/sgg_model_zoo/oi_R152_nm.pth
2. https://penzhanwu2.blob.core.windows.net/phillytools/data/maskrcnn/pretrained_model/sgg_model_zoo/oi_R152_grcnn.pth
3. https://penzhanwu2.blob.core.windows.net/phillytools/data/maskrcnn/pretrained_model/sgg_model_zoo/oi_R152_reldn.pth

Would it be possible to fix them!?

Thanks,
Alessandro

**Comment by hanxiaotian** [comment]
fixed, thanks!

**Comment by KosukeTrue** [comment]
I still can not down load these files
