### ISSUE TITLE
Broken links to VinVL model and associated labelmaps

### ISSUE THREAD

**Issue by stopmosk** [microsoft/scene_graph_benchmark#5]
Hi!
These links are broken (resource not found error):
`https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/vinvl_model_zoo/vinvl_vg_x152c4.pth`
`https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/vinvl_model_zoo/VG-SGG-dicts-vgoi6-clipped.json`

**Comment by pzzhang** [comment]
Please try again. I just make the storage blob public.

**Comment by stopmosk** [comment]
It works, thanks!
