### ISSUE TITLE
where can I find the dataset yaml in the config file?

### ISSUE THREAD

**Issue by runzeer** [microsoft/scene_graph_benchmark#6]
In any config file, I found there existed DATASETS.TRAIN is a yaml dir. But I can not find it.

**Comment by hanxiaotian** [comment]
I add download instruction to the datasets. Please try this. Thanks.

**Comment by runzeer** [comment]
<img width="509" alt="截屏2021-04-14 下午2 41 12" src="https://user-images.githubusercontent.com/14292495/114665363-87111700-9d2f-11eb-9c3a-54c1bd620091.png">
I mean where can I find the yaml file.

**Comment by vinson2233** [comment]
I write my own YAML like this after generating TSV file using tsv_demo.py
```
img : "train.tsv"
label :  "train.label.tsv"
hw : "train.hw.tsv"
linelist : "train.linelist.tsv"
```
It works on my case.

**Comment by runzeer** [comment]
Have you ever run the VINVL code on the VizWiz datasets?  I extracted the img feats and generate the object tags with the same model weights.  But the evaluation results remain same with the training process continues. Is is due to the object tags??

**Comment by vinson2233** [comment]
No, I never try VinVL on VizWiz. I just trying to make VinVL work on my private dataset. Maybe someone else in the future can help.

**Comment by hanxiaotian** [comment]
you can find the dataset yaml file here [test_danfeiX_relation.yaml](https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/datasets/visualgenome/test_danfeiX_relation.yaml)

**Comment by pzzhang** [comment]
@runzeer  We did not try VinVL on the VizWiz datasets
