### ISSUE TITLE
Conflicting version pytorch and torchvision

### ISSUE THREAD

**Issue by rafaelpadilla** [microsoft/scene_graph_benchmark#68]
I have followed the instructions in [INSTALL.md](https://github.com/microsoft/scene_graph_benchmark/blob/main/INSTALL.md), but it shows compatibility error between pytorch and torchvision versions.

![image](https://user-images.githubusercontent.com/31217453/151595108-9663aa9e-3ec1-44b3-a089-b498e87b6cf3.png)

Am I missing something here?

**Comment by albertmundu** [comment]
Check your `torch` and `torchvision` versions and see if they are compatible https://github.com/pytorch/vision#installation.

**Comment by mattsetzler** [comment]
I'm experiencing the same issue. Initially I followed the installation instructions step-by-step. But this resulted in torchvision.__version__ == 0.8.0a0 (as opposed to 0.8.2, which is what corresponds to torch version 1.7.1).

So I then uninstalled torchvision and reinstalled with "pip install torchvision==0.8.2". I can now confirm that my environment contains torch.__version__ == 1.7.1 and torchvision.__version__ 0.8.2. According to https://github.com/pytorch/vision#installation, these are compatible versions, and yet I'm still experiencing the same issue.

**Comment by albertmundu** [comment]
@mattsetzler I too had the same issue. Reinstalling `torch+torchvision` using the `pip`  from https://pytorch.org/get-started/previous-versions/ solved it. Initially, it was installed using `conda` but it failed to install the right version.

**Comment by mattsetzler** [comment]
Thanks @albertmundu. After installing `torch+torchvision` from `pip` things seem to be working fine. I had to also install `timm` from `pip`, because doing so via `conda` would have changed my `torchvision` version.

**Comment by rafaelpadilla** [comment]
Thanks @albertmundu @mattsetzler :) 
Problem solved! 
I will close this issue. Thank you!
