### ISSUE TITLE
Runtime error occurred when extracting features for VinVL (running train_sg_net.py).

### ISSUE THREAD

**Issue by KatieGou** [microsoft/scene_graph_benchmark#73]
When I ran tools/train_sg_net.py with command 
_python tools/test_sg_net.py --config sgg_configs/vgattr/vinvl_x152c4.yaml TEST.IMS_PER_BATCH 1 MODEL.WEIGHT models/vinvl/vinvl_vg_x152c4.pth MODEL.ROI_HEADS.NMS_FILTER 1 MODEL.ROI_HEADS.SCORE_THRESH 0.2 DATA_DIR models/vinvl/ TEST.IGNORE_BOX_REGRESSION True MODEL.ATTRIBUTE_ON True TEST.OUTPUT_FEATURE True_ 

For every image, I got error: 
__Runtime error occurred in Image Ids: xxx_, 
followed by 
_Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install._ 

The pytorch version is 1.71. and torchvision version is 0.8.2. 

I have added _feature_ in _TEST.TSV_SAVE_SUBSET_ and changed the test file to _test_danfeiX_relation.yaml_. 

Meanwhile, I didn't get the instruction _in yaml file, set TEST.OUTPUT_FEATURE to True_ because there is no _OUTPUT_FEATURE_ in file _sgg_configs/vgattr/vinvl_x152c4.yaml_. 

Could anyone help me out?

**Comment by ignasa007** [comment]
Hey, how did you fix it?
